bag[0]:
bag[1]:
bag[2]:
bag[3]:
bag[4]:
bag[5]:
bag[6]:
bag[7]:
bag[8]:
bag[9]:
bag[10]:
bag[11]:
bag[12]:
bag[13]:
bag[14]:
bag[15]:
bag[16]:
bag[17]:
bag[18]:
bag[19]:
bag[20]:
bag[21]:
bag[22]:
bag[23]:
bag[24]:
bag[25]:
bag[26]:
bag[27]:
bag[28]:
bag[29]:
bag[30]:
bag[31]:
bag[32]:
bag[33]:
bag[34]:
bag[35]:
helmet:
chestplate:
leggings:
boots:
